version: '3.8'

volumes:
  ts_core_db_data:
  ts_core_static:
  ts_core_media:

networks:
  ts_core_network:
    driver: bridge

services:

  # PostgreSQL
  ts_core_db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - ts_core_db_data:/var/lib/postgresql/data
    networks:
      - ts_core_network
    restart: unless-stopped

  # Django backend
  ts_core_backend:
    image: alexandercholiy/ts_core_backend
    env_file: .env
    volumes:
      - ts_core_static:/backend_static
      - ts_core_media:/app/media/
    depends_on:
      - ts_core_db
    networks:
      - ts_core_network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    command: >
      sh -c "
        python manage.py makemigrations &&
        python manage.py migrate &&
        python manage.py add_default_admin &&
        python manage.py collectstatic --noinput &&
        cp -r /app/collected_static/. /backend_static/ &&
        gunicorn backend.wsgi:application --bind 0.0.0.0:8000
      "

  # Nginx
  ts_core_gateway:
    image: alexandercholiy/ts_core_gateway
    ports:
      - "8000:80"
    volumes:
      - ts_core_static:/staticfiles/
      - ts_core_media:/mediafiles/
    depends_on:
      - ts_core_backend
    networks:
      - ts_core_network
    restart: unless-stopped
