# Generated by Django 5.0.14 on 2025-07-01 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(db_column='StatusID', primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, db_column='StatusDesc', max_length=255, null=True)),
            ],
            options={
                'db_table': 'MSys_Statuses',
                'managed': False,
            },
        ),
    ]
