# Generated by Django 5.0.14 on 2025-07-02 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.CharField(db_column='CounterID', max_length=20, primary_key=True, serialize=False, verbose_name='Номер счетчика')),
                ('number', models.PositiveIntegerField(blank=True, db_column='CounterNumber', null=True, verbose_name='Порядковый номер')),
            ],
            options={
                'verbose_name': 'счётчик',
                'verbose_name_plural': 'Счётчики',
                'db_table': 'MSys_Counters',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Modem',
            fields=[
                ('id', models.CharField(db_column='ModemID', max_length=20, primary_key=True, serialize=False, verbose_name='IP модема')),
                ('level', models.IntegerField(db_column='ModemLevel', verbose_name='Тип устройсва')),
                ('phone', models.CharField(blank=True, db_column='ModemMsisdn', max_length=20, null=True, verbose_name='Телефон')),
                ('status_timestamp', models.DateTimeField(blank=True, db_column='ModemAlarmtimestamp', null=True, verbose_name='Время изменения статуса')),
                ('mac', models.CharField(blank=True, db_column='ModemCounter', max_length=30, null=True, verbose_name='MAC-адрес')),
                ('serial', models.CharField(blank=True, db_column='ModemSerial', max_length=30, null=True, verbose_name='Серийный номер')),
                ('imsi', models.CharField(blank=True, db_column='ModemIMSI', max_length=30, null=True, verbose_name='серийный номер sim карты')),
                ('version', models.CharField(blank=True, db_column='ModemVersion', max_length=10, null=True, verbose_name='Версия контроллера')),
                ('latitude', models.CharField(blank=True, db_column='ModemLatitude', max_length=12, null=True, verbose_name='Широта')),
                ('longtitude', models.CharField(blank=True, db_column='ModemLongtitude', max_length=15, null=True, verbose_name='Долгота')),
                ('firmware', models.CharField(blank=True, db_column='ModemFirmware', max_length=30, null=True, verbose_name='Прошивка')),
                ('watchdog', models.IntegerField(blank=True, db_column='ModemWatchdog', null=True, verbose_name='датчик двери')),
                ('cabinet_serial', models.CharField(blank=True, db_column='ModemCabinetSerial', max_length=30, null=True, verbose_name='Серийный номер шкафа')),
            ],
            options={
                'verbose_name': 'модем',
                'verbose_name_plural': 'Модемы',
                'db_table': 'MSys_Modems',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.AutoField(db_column='OrgID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='OrgName', max_length=30, null=True, verbose_name='Название')),
                ('st_name', models.CharField(blank=True, db_column='OrgShort', max_length=5, null=True, verbose_name='Аббревиатура')),
            ],
            options={
                'verbose_name': 'оператор',
                'verbose_name_plural': 'Операторы',
                'db_table': 'Msys_Orgs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pole',
            fields=[
                ('id', models.CharField(db_column='PoleID', max_length=20, primary_key=True, serialize=False, verbose_name='Шифр опоры')),
                ('address', models.CharField(blank=True, db_column='PoleAddress', max_length=512, null=True, verbose_name='Адрес')),
                ('latitude', models.FloatField(blank=True, db_column='PoleLatitude', null=True, verbose_name='Широта')),
                ('longitude', models.FloatField(blank=True, db_column='PoleLongtitude', null=True, verbose_name='Долгота')),
                ('master', models.CharField(blank=True, db_column='PoleMaster', max_length=20, null=True, verbose_name='Мастер опора')),
                ('on_air_date', models.DateField(blank=True, db_column='PoleOnAirDate', null=True, verbose_name='Дата включения')),
            ],
            options={
                'verbose_name': 'опора',
                'verbose_name_plural': 'Опоры',
                'db_table': 'Msys_Poles',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'managed': False, 'verbose_name': 'статус', 'verbose_name_plural': 'Статусы'},
        ),
    ]
